name: server CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://www.github.com/iamjooon2/GridgeTestChallenge"

      - name: Create .env file
        run: |
          cd /home/ubuntu/server
          touch << EDF >> .env.development
          ${{ secrets.ENV_DEVLOPMENT }}

      - name: executing remote ssh commands
        uses: actions/setup-node@v1
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/server/GridgeTestChallenge
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm ci
            npm install
            pm2 restart src/app.js